-- Mission Ops Lite Snowflake OLAP schema setup
-- Replace warehouse/database names as needed in a real Snowflake environment.

CREATE WAREHOUSE IF NOT EXISTS MISSION_OPS_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS MISSION_OPS_LITE;
CREATE SCHEMA IF NOT EXISTS MISSION_OPS_LITE.OLAP;

USE WAREHOUSE MISSION_OPS_WH;
USE DATABASE MISSION_OPS_LITE;
USE SCHEMA OLAP;
