-- Gold-layer OLAP table contracts for curated Spark/Databricks outputs.

USE DATABASE MISSION_OPS_LITE;
USE SCHEMA OLAP;

CREATE TABLE IF NOT EXISTS GOLD_ORBIT_FRESHNESS_METRICS (
  METRIC_DATE DATE NOT NULL,
  SOURCE_NAME VARCHAR NOT NULL,
  FRESHNESS_STATUS VARCHAR NOT NULL,
  QUALITY_STATUS VARCHAR NOT NULL,
  SATELLITE_COUNT NUMBER NOT NULL,
  AVG_EPOCH_AGE_HOURS FLOAT,
  MIN_EPOCH_AGE_HOURS FLOAT,
  MAX_EPOCH_AGE_HOURS FLOAT,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE FILE FORMAT MISSION_OPS_PARQUET_FORMAT
  TYPE = PARQUET
  USE_VECTORIZED_SCANNER = TRUE;

CREATE STAGE IF NOT EXISTS MISSION_OPS_GOLD_STAGE
  FILE_FORMAT = MISSION_OPS_PARQUET_FORMAT;
